In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [4]:
df= pd.read_csv("/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv")

In [5]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [10]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [11]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [13]:
df.drop(columns=["RowNumber", "CustomerId", "Surname"], inplace=True)

In [23]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [21]:
pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True).dtype="int"

In [22]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [18]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [24]:
df = pd.get_dummies(
    df,
    columns=["Geography", "Gender"],
    drop_first=True,
    dtype=int
)

In [25]:
print(df)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1
1             608   41       1   83807.86              1          0
2             502   42       8  159660.80              3          1
3             699   39       1       0.00              2          0
4             850   43       2  125510.82              1          1
...           ...  ...     ...        ...            ...        ...
9995          771   39       5       0.00              2          1
9996          516   35      10   57369.61              1          1
9997          709   36       7       0.00              1          0
9998          772   42       3   75075.31              2          1
9999          792   28       4  130142.79              1          1

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1                  0
1                  1        112542.58       0                  0
2                  0        113931.57       1                  0
3                  0         93826.63       0                  0
4                  1         79084.10       0                  0
...              ...              ...     ...                ...
9995               0         96270.64       0                  0
9996               1        101699.77       0                  0
9997               1         42085.58       1                  0
9998               0         92888.52       1                  1
9999               0         38190.78       0                  0

      Geography_Spain  Gender_Male
0                   0            0
1                   1            0
2                   0            0
3                   0            0
4                   1            0
...               ...          ...
9995                0            1
9996                0            1
9997                0            0
9998                0            1
9999                0            0

[10000 rows x 12 columns]

In [29]:
X=df.drop(columns=["Exited"])
y=df["Exited"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [31]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler=StandardScaler()

In [35]:
X_train_scaled=scaler.fit_transform(X_train)
y_test_scaled=scaler.transform(X_test)

In [50]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]], shape=(8000, 11))

In [39]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [40]:
model=Sequential()

In [41]:
model.add(Dense(3,activation="sigmoid",input_dim=11))   #input layer
model.add(Dense(1,activation="sigmoid"))                #output layer

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-06-17 12:28:29.760564: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [43]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(loss="binary_crossentropy",optimizer="Adam")

In [46]:
model.fit(X_train_scaled,y_train,epochs=109)

Epoch 1/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6075
Epoch 2/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5286
Epoch 3/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4955
Epoch 4/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4760
Epoch 5/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4622
Epoch 6/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4516
Epoch 7/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4437
Epoch 8/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4379
Epoch 9/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4339
Epoch 10/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4311
Epoch 11/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4291
Epoch 12/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4277
Epoch 13/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4265
Epoch 14/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4255
Epoch 15/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4245
Epoch 16/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4235
Epoch 17/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4224
Epoch 18/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4213
Epoch 19/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4200
Epoch 20/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4188
Epoch 21/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4175
Epoch 22/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4164
Epoch 23/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4153
Epoch 24/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4144
Epoch 25/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4134
Epoch 26/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4126
Epoch 27/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4119
Epoch 28/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4112
Epoch 29/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4106
Epoch 30/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4101
Epoch 31/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4096
Epoch 32/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4091
Epoch 33/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4088
Epoch 34/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4084
Epoch 35/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4081
Epoch 36/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4078
Epoch 37/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4075
Epoch 38/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4073
Epoch 39/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4071
Epoch 40/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4068
Epoch 41/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4066
Epoch 42/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4064
Epoch 43/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4063
Epoch 44/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4062
Epoch 45/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4060
Epoch 46/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4059
Epoch 47/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4057
Epoch 48/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4057
Epoch 49/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4055
Epoch 50/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4054
Epoch 51/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4053
Epoch 52/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4052
Epoch 53/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4052
Epoch 54/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4050
Epoch 55/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4050
Epoch 56/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4049
Epoch 57/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4048
Epoch 58/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4047
Epoch 59/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4046
Epoch 60/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4046
Epoch 61/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4045
Epoch 62/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4045
Epoch 63/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4044
Epoch 64/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4044
Epoch 65/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4042
Epoch 66/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4043
Epoch 67/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4042
Epoch 68/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4042
Epoch 69/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4041
Epoch 70/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4041
Epoch 71/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4040
Epoch 72/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4040
Epoch 73/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4039
Epoch 74/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4039
Epoch 75/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4039
Epoch 76/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4039
Epoch 77/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4038
Epoch 78/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4038
Epoch 79/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4037
Epoch 80/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4037
Epoch 81/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4037
Epoch 82/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4036
Epoch 83/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4036
Epoch 84/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4036
Epoch 85/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4036
Epoch 86/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4036
Epoch 87/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4035
Epoch 88/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4035
Epoch 89/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4035
Epoch 90/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4034
Epoch 91/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4034
Epoch 92/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4034
Epoch 93/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4034
Epoch 94/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4034
Epoch 95/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4033
Epoch 96/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4033
Epoch 97/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4033
Epoch 98/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4033
Epoch 99/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4033
Epoch 100/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4033
Epoch 101/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4032
Epoch 102/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4032
Epoch 103/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4032
Epoch 104/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4032
Epoch 105/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4031
Epoch 106/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4031
Epoch 107/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4031
Epoch 108/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4031
Epoch 109/109
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4031

In [48]:
model.layers[1].get_weights()

[array([[-1.3462077],
        [ 1.9164904],
        [-2.924036 ]], dtype=float32),
 array([-0.24736391], dtype=float32)]

In [52]:
model.predict(X_test_scaled)

NameError: name 'X_test_scaled' is not defined

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

NameError: name 'y_pred' is not defined